In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('irrigation_prediction.csv')
df.head()

,type_sol,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,type_culture,stade_croissance,saison,type_irrigation,source_eau,surface_champ,paillage,irrigation_precedente,region,besoin_irrigation
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_sol                 10000 non-null  object
 1   ph_sol                   10000 non-null  float64
 2   humidite_sol             10000 non-null  float64
 3   carbone_organique        10000 non-null  float64
 4   conductivite_electrique  10000 non-null  float64
 5   temperature              10000 non-null  float64
 6   humidite                 10000 non-null  float64
 7   precipitation            10000 non-null  float64
 8   heures_ensoleillement    10000 non-null  float64
 9   vitesse_vent             10000 non-null  float64
 10  type_culture             10000 non-null  object
 11  stade_croissance         10000 non-null  object
 12  saison                   10000 non-null  object
 13  type_irrigation          10000 non-null  object
 14  source_eau               10000 non-null  object
 15  surface_champ            10000 non-null  float64
 16  paillage                 10000 non-null  object
 17  irrigation_precedente    10000 non-null  float64
 18  region                   10000 non-null  object
 19  besoin_irrigation        10000 non-null  object
dtypes: float64(11), object(9)
memory usage: 1.5+ MB

In [4]:
df.describe()

,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,surface_champ,irrigation_precedente
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,6.487857,36.969207,0.944731,1.791963,26.991423,60.080339,1252.499420,7.518538,10.163545,7.598024,59.864122
std,0.979963,16.430845,0.372406,0.984202,8.664074,20.187973,715.582201,2.016077,5.670923,4.233919,34.483722
min,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,5.640000,22.860000,0.620000,0.940000,19.460000,42.855000,634.155000,5.760000,5.160000,3.950000,30.160000
50%,6.470000,37.240000,0.950000,1.780000,27.090000,60.040000,1250.335000,7.560000,10.190000,7.540000,59.630000
75%,7.350000,50.940000,1.260000,2.650000,34.500000,77.705000,1880.265000,9.260000,15.100000,11.202500,90.030000
max,8.200000,65.000000,1.600000,3.500000,42.000000,95.000000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [5]:
# dictionnaire pour renommer les colonnes
# (noms plus simples et standard pour ML)
new_columns = {
    "Soil_Type": "type_sol",
    "Soil_pH": "ph_sol",
    "Soil_Moisture": "humidite_sol",
    "Organic_Carbon": "carbone_organique",
    "Electrical_Conductivity": "conductivite_electrique",
    "Temperature_C": "temperature",
    "Humidity": "humidite",
    "Rainfall_mm": "precipitation",
    "Sunlight_Hours": "heures_ensoleillement",
    "Wind_Speed_kmh": "vitesse_vent",
    "Crop_Type": "type_culture",
    "Crop_Growth_Stage": "stade_croissance",
    "Season": "saison",
    "Irrigation_Type": "type_irrigation",
    "Water_Source": "source_eau",
    "Field_Area_hectare": "surface_champ",
    "Mulching_Used": "paillage",
    "Previous_Irrigation_mm": "irrigation_precedente",
    "Region": "region",
    "Irrigation_Need": "besoin_irrigation"
}

# appliquer le renommage
df = df.rename(columns=new_columns)

# sauvegarder le fichier nettoyé
df.to_csv("irrigation_prediction.csv", index=False)

print("Colonnes renommées avec succès")

Colonnes renommées avec succès

In [6]:
df.head()

,type_sol,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,type_culture,stade_croissance,saison,type_irrigation,source_eau,surface_champ,paillage,irrigation_precedente,region,besoin_irrigation
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

# Description des colonnes :
## des information sur le sol : 

#### type_sol
    Type de sol (argileux, sableux...)
Sert à déterminer la capacité du sol à retenir l’eau
#### ph_sol
     Niveau d’acidité du sol
Influence l’absorption des nutriments et de l’eau
#### humidite_sol
     Quantité d’eau présente dans le sol
Indicateur principal pour décider l’irrigation
#### carbone_organique
    Matière organique dans le sol
Améliore la fertilité et la rétention d’eau
#### conductivite_electrique
    Niveau de salinité du sol
Un sol trop salé peut nuire à la plante

## Conditions climatiques
#### temperature
    Température ambiante
Influence l’évaporation de l’eau
#### humidite
    Humidité de l’air
Affecte la perte d’eau par évaporation
#### precipitation
    Quantité de pluie
Peut réduire ou remplacer l’irrigation
#### heures_ensoleillement
    Nombre d’heures de soleil
Plus de soleil = plus d’évaporation
#### vitesse_vent
    Vitesse du vent
Accélère le séchage du sol
## Culture
#### type_culture
    Type de plante cultivée
Chaque culture a des besoins en eau différents
#### stade_croissance
    Stade de développement de la plante
Les besoins en eau varient selon le stade
#### saison
    Saison de culture
Impacte les conditions climatiques
## Irrigation
### type_irrigation
    Méthode d’irrigation (goutte-à-goutte, aspersion...)
Influence l’efficacité de l’eau utilisée
#### source_eau
    Origine de l’eau (puits, rivière...)
Peut influencer la disponibilité
#### surface_champ
    Taille du champ (en hectares)
Détermine la كمية totale d’eau nécessaire
#### paillage
    Utilisation de paillage (oui/non)
Réduit l’évaporation et conserve l’humidité
#### irrigation_precedente
    Quantité d’eau utilisée précédemment
Aide à éviter le sur-arrosage

In [7]:
df = df.drop_duplicates()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_sol                 10000 non-null  object
 1   ph_sol                   10000 non-null  float64
 2   humidite_sol             10000 non-null  float64
 3   carbone_organique        10000 non-null  float64
 4   conductivite_electrique  10000 non-null  float64
 5   temperature              10000 non-null  float64
 6   humidite                 10000 non-null  float64
 7   precipitation            10000 non-null  float64
 8   heures_ensoleillement    10000 non-null  float64
 9   vitesse_vent             10000 non-null  float64
 10  type_culture             10000 non-null  object
 11  stade_croissance         10000 non-null  object
 12  saison                   10000 non-null  object
 13  type_irrigation          10000 non-null  object
 14  source_eau               10000 non-null  object
 15  surface_champ            10000 non-null  float64
 16  paillage                 10000 non-null  object
 17  irrigation_precedente    10000 non-null  float64
 18  region                   10000 non-null  object
 19  besoin_irrigation        10000 non-null  object
dtypes: float64(11), object(9)
memory usage: 1.5+ MB

In [8]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_sol                 10000 non-null  object
 1   ph_sol                   10000 non-null  float64
 2   humidite_sol             10000 non-null  float64
 3   carbone_organique        10000 non-null  float64
 4   conductivite_electrique  10000 non-null  float64
 5   temperature              10000 non-null  float64
 6   humidite                 10000 non-null  float64
 7   precipitation            10000 non-null  float64
 8   heures_ensoleillement    10000 non-null  float64
 9   vitesse_vent             10000 non-null  float64
 10  type_culture             10000 non-null  object
 11  stade_croissance         10000 non-null  object
 12  saison                   10000 non-null  object
 13  type_irrigation          10000 non-null  object
 14  source_eau               10000 non-null  object
 15  surface_champ            10000 non-null  float64
 16  paillage                 10000 non-null  object
 17  irrigation_precedente    10000 non-null  float64
 18  region                   10000 non-null  object
 19  besoin_irrigation        10000 non-null  object
dtypes: float64(11), object(9)
memory usage: 1.5+ MB

In [9]:
# supprition des valeurs aberantes 
df = df[df['temperature'] < 60]
df = df[(df['humidite_sol'] >= 0) & (df['humidite_sol'] <= 100)]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type_sol                 10000 non-null  object
 1   ph_sol                   10000 non-null  float64
 2   humidite_sol             10000 non-null  float64
 3   carbone_organique        10000 non-null  float64
 4   conductivite_electrique  10000 non-null  float64
 5   temperature              10000 non-null  float64
 6   humidite                 10000 non-null  float64
 7   precipitation            10000 non-null  float64
 8   heures_ensoleillement    10000 non-null  float64
 9   vitesse_vent             10000 non-null  float64
 10  type_culture             10000 non-null  object
 11  stade_croissance         10000 non-null  object
 12  saison                   10000 non-null  object
 13  type_irrigation          10000 non-null  object
 14  source_eau               10000 non-null  object
 15  surface_champ            10000 non-null  float64
 16  paillage                 10000 non-null  object
 17  irrigation_precedente    10000 non-null  float64
 18  region                   10000 non-null  object
 19  besoin_irrigation        10000 non-null  object
dtypes: float64(11), object(9)
memory usage: 1.5+ MB

In [12]:
# normalisation et la standardisation 
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['temperature','humidite_sol','humidite']] = scaler.fit_transform(
    df[['temperature','humidite_sol','humidite']]
)

In [13]:
#pour transformer les variable categorielles on des variables numeriques
df = pd.get_dummies(df, drop_first=True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ph_sol                       10000 non-null  float64
 1   humidite_sol                 10000 non-null  float64
 2   carbone_organique            10000 non-null  float64
 3   conductivite_electrique      10000 non-null  float64
 4   temperature                  10000 non-null  float64
 5   humidite                     10000 non-null  float64
 6   precipitation                10000 non-null  float64
 7   heures_ensoleillement        10000 non-null  float64
 8   vitesse_vent                 10000 non-null  float64
 9   surface_champ                10000 non-null  float64
 10  irrigation_precedente        10000 non-null  float64
 11  type_sol_Loamy               10000 non-null  bool
 12  type_sol_Sandy               10000 non-null  bool
 13  type_sol_Silt                10000 non-null  bool
 14  type_culture_Maize           10000 non-null  bool
 15  type_culture_Potato          10000 non-null  bool
 16  type_culture_Rice            10000 non-null  bool
 17  type_culture_Sugarcane       10000 non-null  bool
 18  type_culture_Wheat           10000 non-null  bool
 19  stade_croissance_Harvest     10000 non-null  bool
 20  stade_croissance_Sowing      10000 non-null  bool
 21  stade_croissance_Vegetative  10000 non-null  bool
 22  saison_Rabi                  10000 non-null  bool
 23  saison_Zaid                  10000 non-null  bool
 24  type_irrigation_Drip         10000 non-null  bool
 25  type_irrigation_Rainfed      10000 non-null  bool
 26  type_irrigation_Sprinkler    10000 non-null  bool
 27  source_eau_Rainwater         10000 non-null  bool
 28  source_eau_Reservoir         10000 non-null  bool
 29  source_eau_River             10000 non-null  bool
 30  paillage_Yes                 10000 non-null  bool
 31  region_East                  10000 non-null  bool
 32  region_North                 10000 non-null  bool
 33  region_South                 10000 non-null  bool
 34  region_West                  10000 non-null  bool
 35  besoin_irrigation_Low        10000 non-null  bool
 36  besoin_irrigation_Medium     10000 non-null  bool
dtypes: bool(26), float64(11)
memory usage: 1.1 MB

In [15]:
df.head()

,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,surface_champ,...,source_eau_Rainwater,source_eau_Reservoir,source_eau_River,paillage_Yes,region_East,region_North,region_South,region_West,besoin_irrigation_Low,besoin_irrigation_Medium
0,6.14,-0.029775,-1.409102,2.17,-0.587677,-1.431138,1167.70,4.01,1.97,4.73,...,False,True,False,True,False,False,True,False,True,False
1,6.41,0.827193,-1.516517,0.23,1.097527,-1.687740,831.28,10.72,16.82,12.22,...,False,False,False,True,False,False,False,False,False,True
2,7.71,0.188727,0.390102,2.18,1.712741,0.808921,1844.45,7.75,19.03,5.52,...,False,True,False,True,False,False,True,False,True,False
3,5.96,-1.474082,1.652230,0.40,1.180633,-0.830256,306.26,8.90,11.44,1.43,...,False,True,False,True,False,True,False,False,False,True
4,7.76,-1.119244,0.014149,2.52,-0.532273,1.305776,1875.63,10.39,11.26,2.52,...,False,False,True,False,False,False,True,False,False,True

In [16]:
df.shape

(10000, 37)

In [17]:
# Étape 1 : Créer une seule colonne "target" à partir des colonnes encodées
# idxmax(axis=1) permet de récupérer le nom de la colonne qui contient la valeur 1 (la classe active)
df['target'] = df[['besoin_irrigation_Low', 'besoin_irrigation_Medium']].idxmax(axis=1)


# Étape 2 : Transformer les valeurs textuelles en valeurs numériques
# On convertit :
# 'besoin_irrigation_Low' → 0
# 'besoin_irrigation_Medium' → 1
df['target'] = df['target'].map({
    'besoin_irrigation_Low': 0,
    'besoin_irrigation_Medium': 1
})


# Étape 3 : Supprimer les anciennes colonnes (one-hot encoding)
# Ces colonnes ne sont plus nécessaires après la création de la target
df = df.drop(['besoin_irrigation_Low', 'besoin_irrigation_Medium'], axis=1)


# Étape 4 (optionnelle) : Vérification
# Afficher les premières lignes pour confirmer que tout est correct
df.head()

,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,surface_champ,...,type_irrigation_Sprinkler,source_eau_Rainwater,source_eau_Reservoir,source_eau_River,paillage_Yes,region_East,region_North,region_South,region_West,target
0,6.14,-0.029775,-1.409102,2.17,-0.587677,-1.431138,1167.70,4.01,1.97,4.73,...,False,False,True,False,True,False,False,True,False,0
1,6.41,0.827193,-1.516517,0.23,1.097527,-1.687740,831.28,10.72,16.82,12.22,...,False,False,False,False,True,False,False,False,False,1
2,7.71,0.188727,0.390102,2.18,1.712741,0.808921,1844.45,7.75,19.03,5.52,...,False,False,True,False,True,False,False,True,False,0
3,5.96,-1.474082,1.652230,0.40,1.180633,-0.830256,306.26,8.90,11.44,1.43,...,False,False,True,False,True,False,True,False,False,1
4,7.76,-1.119244,0.014149,2.52,-0.532273,1.305776,1875.63,10.39,11.26,2.52,...,False,False,False,True,False,False,False,True,False,1

In [18]:
# transformer les colonnes que contien la variable bool en int 
bool_cols = df.select_dtypes(include=['bool']).columns

df[bool_cols] = df[bool_cols].astype(int)

In [19]:
df.head()

,ph_sol,humidite_sol,carbone_organique,conductivite_electrique,temperature,humidite,precipitation,heures_ensoleillement,vitesse_vent,surface_champ,...,type_irrigation_Sprinkler,source_eau_Rainwater,source_eau_Reservoir,source_eau_River,paillage_Yes,region_East,region_North,region_South,region_West,target
0,6.14,-0.029775,-1.409102,2.17,-0.587677,-1.431138,1167.70,4.01,1.97,4.73,...,0,0,1,0,1,0,0,1,0,0
1,6.41,0.827193,-1.516517,0.23,1.097527,-1.687740,831.28,10.72,16.82,12.22,...,0,0,0,0,1,0,0,0,0,1
2,7.71,0.188727,0.390102,2.18,1.712741,0.808921,1844.45,7.75,19.03,5.52,...,0,0,1,0,1,0,0,1,0,0
3,5.96,-1.474082,1.652230,0.40,1.180633,-0.830256,306.26,8.90,11.44,1.43,...,0,0,1,0,1,0,1,0,0,1
4,7.76,-1.119244,0.014149,2.52,-0.532273,1.305776,1875.63,10.39,11.26,2.52,...,0,0,0,1,0,0,0,1,0,1

In [20]:
df.dtypes

ph_sol                         float64
humidite_sol                   float64
carbone_organique              float64
conductivite_electrique        float64
temperature                    float64
humidite                       float64
precipitation                  float64
heures_ensoleillement          float64
vitesse_vent                   float64
surface_champ                  float64
irrigation_precedente          float64
type_sol_Loamy                   int64
type_sol_Sandy                   int64
type_sol_Silt                    int64
type_culture_Maize               int64
type_culture_Potato              int64
type_culture_Rice                int64
type_culture_Sugarcane           int64
type_culture_Wheat               int64
stade_croissance_Harvest         int64
stade_croissance_Sowing          int64
stade_croissance_Vegetative      int64
saison_Rabi                      int64
saison_Zaid                      int64
type_irrigation_Drip             int64
type_irrigation_Rainfed          int64
type_irrigation_Sprinkler        int64
source_eau_Rainwater             int64
source_eau_Reservoir             int64
source_eau_River                 int64
paillage_Yes                     int64
region_East                      int64
region_North                     int64
region_South                     int64
region_West                      int64
target                           int64
dtype: object

In [22]:
df.to_csv("clean_data.csv", index=False)